In [ ]:
# Install required libraries
!pip install airtable-python-wrapper

Requirement already satisfied: airtable-python-wrapper in /usr/local/lib/python3.10/dist-packages (0.15.3)
Requirement already satisfied: requests>=2 in /usr/local/lib/python3.10/dist-packages (from airtable-python-wrapper) (2.31.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2->airtable-python-wrapper) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2->airtable-python-wrapper) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2->airtable-python-wrapper) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2->airtable-python-wrapper) (2023.7.22)

In [ ]:
# Import libraries
import pandas as pd
from airtable import Airtable

In [ ]:
# Replace these with your actual Airtable information
AIRTABLE_API_KEY = ""
AIRTABLE_BASE_ID = ""
AIRTABLE_TABLE_NAME = ""
AIRTABLE_VIEW = ""  # Replace with the desired view name

In [ ]:
# Connect to Airtable
airtable = Airtable(AIRTABLE_BASE_ID, AIRTABLE_TABLE_NAME, api_key=AIRTABLE_API_KEY)

In [ ]:
# Get all records from Airtable
records = airtable.get_all(view=AIRTABLE_VIEW)

In [ ]:
# Convert records to a list of dictionaries
data = [record['fields'] for record in records]

In [ ]:
df = pd.DataFrame(data)

In [ ]:
df.head()

,PAIS,Español,Portugués,TITULO_ESP,Dirección,Inicial/Final,DAP,Clientes,IMP_ESP,RESPONSABLE_OBRA,...,EXPEDIENTE_MUNI,TX_RR,FOTO_Pendiente,Español_JO,JO_OK,CATASTRO_AREA,CHILE_PARTE,NOTA_ALTERNATIVA,ComentariosLLANOS,Done
0,USA,Trabajos de conservación en este emblemático e...,Trabalho de conservação neste emblemático edif...,"Upper East Side, Manhattan","4 E 74th St, New York, NY 10021, Estados Unidos",Final,DAP,PATRIMONIALES,"[{'id': 'attLAS9nPP96UrFuU', 'url': 'https://v...",[rec3zFKIx52e8n3KY],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,USA,Restauración completa de la ventana oriel en e...,Restauração completa da janela do oriel no Dis...,92 St James Pl.,"92 St James Pl, Brooklyn, NY 11238, EE. UU.",Final,DAP,PATRIMONIALES,"[{'id': 'attt3G9P0W7wJO05d', 'url': 'https://v...",[rec3zFKIx52e8n3KY],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Recibimos el encargo de rehabilitar el interio...,Fomos encarregados de remodelar o interior da ...,1083 Quinta Avenida,"1083 5th Ave, New York, NY 10128, USA",Inicial,NaN,PATRIMONIALES,"[{'id': 'attrVq7tHEcQvwEae', 'url': 'https://v...",[rec3zFKIx52e8n3KY],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,FRANCIA,La Real Abadía de Nuestra Señora de Fontevraud...,A Abadia Real de Nossa Senhora de Fontevraud e...,Abadía Real,"49590 Fontevraud-l'Abbaye, Francia",Final,NaN,IGLESIA / GEST PATRIM PUBL,"[{'id': 'attP3hODPzi6G3U8i', 'url': 'https://v...",[recbhkBFVeD1zynOy],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ESPAÑA,En el Antiguo Parador del Rey se realizan obra...,"No antigo Parador del Rey, os trabalhos estão ...",Abastos 56,"Calle de Abastos, 56, 28300 Aranjuez, Madrid",Final,NaN,CP_CENTRO,"[{'id': 'att1yKKDdwYnGg907', 'url': 'https://v...",[recT6O1Aufm09jZnd],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN